# Docker イメージの発行
# https://docs.github.com/ja/actions/publishing-packages/publishing-docker-images

# ワークフローの手動実行
# https://docs.github.com/ja/actions/using-workflows/manually-running-a-workflow

# GitHub Actionsを手動実行するworkflow_dispatch
# https://rcmdnk.com/blog/2023/01/23/computer-github/

# GitHub Actionsでコンテナイメージ作成時に手軽にタグ付けする
# https://techblog.ap-com.co.jp/entry/2023/08/11/111111

# GitHub Actions でのシークレットの使用
# https://docs.github.com/ja/actions/security-guides/using-secrets-in-github-actions?tool=webui


# このワークフローはGitHubによって認定されていないアクションを使用します。
# それらはサードパーティによって提供され、
# 別個の利用規約、プライバシーポリシー、
# ドキュメントを参照してください。

# GitHub では、コミット SHA にアクションをピン留めすることが推奨されます。
# 新しいバージョンを取得するには、SHA を更新する必要があります。
# タグまたはブランチを参照することもできますが、アクションは警告なしに変更される可能性があります。

name: publish-docker-image

on:
  workflow_dispatch:
    inputs:
      osType:
        required: true
        description: OSの種類
        default: windows
     environment:
        required: true
        description: 実行環境
        type: environment

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: shibukit/ubupy6
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./231231_python/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
